# GoReleaser configuration for Michishirube
# https://goreleaser.com

# Configuration version
version: 2

# Project information
project_name: michishirube

# Before hooks for preparation
before:
  hooks:
    # Ensure docs are generated
    - test -f docs/docs.go || make docs

# Build configuration
builds:
  # Darwin builds with CGO
  - id: michishirube-darwin
    main: ./cmd/server
    binary: michishirube
    
    # Environment variables for the build
    env:
      - CGO_ENABLED=1  # Required for SQLite
    
    # Build for Darwin only (CGO works natively)
    goos:
      - darwin
    
    goarch:
      - amd64
      - arm64
    
    # Build flags and ldflags for optimization and version info
    flags:
      - -trimpath
    
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
    
    # Build tags (if needed)
    tags:
      - sqlite_omit_load_extension

  # Linux builds using pure Go SQLite
  - id: michishirube-linux
    main: ./cmd/server
    binary: michishirube
    
    # Environment variables for pure Go build
    env:
      - CGO_ENABLED=0  # Pure Go for cross-compilation
    
    # Build for Linux
    goos:
      - linux
    
    goarch:
      - amd64
      - arm64
    
    # Build flags and ldflags for optimization and version info
    flags:
      - -trimpath
    
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
    
    # Use pure Go SQLite driver
    tags:
      - purego

# Archive configuration
archives:
  - id: michishirube
    name_template: "michishirube_{{.Version}}_{{.Os}}_{{.Arch}}"
    
    # Files to include in archives
    files:
      - README.md
      - CLAUDE.md
      - docs/*
      - web/templates/*
      - web/static/**/*
    
    # Wrap binaries in folder with version name
    wrap_in_directory: true

# Checksum configuration
checksum:
  name_template: "checksums.txt"
  algorithm: sha256

# Snapshot configuration for dev builds
snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"

# Changelog configuration
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - typo
      - merge conflict
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: "New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Documentation Updates"
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Other Changes"
      order: 999

# Release configuration
release:
  # Repo to upload releases
  github:
    owner: jparrill
    name: michishirube
  
  # Draft release for manual review
  draft: true
  
  # Create release even with no new changes
  skip_upload: false
  
  # Release name template
  name_template: "Michishirube v{{.Version}}"
  
  # Release notes
  header: |
    ## Michishirube v{{.Version}}
    
    Personal task management application for developers.
    
    ### Downloads
    
    Download the appropriate binary for your platform below.
    
  footer: |
    ## Installation
    
    1. Download the appropriate binary for your platform
    2. Extract the archive
    3. Run `./michishirube` to start the server
    4. Open http://localhost:8080 in your browser
    
    ## Documentation
    
    - API Documentation: http://localhost:8080/docs
    - OpenAPI Spec: http://localhost:8080/openapi.yaml
    
    ---
    
    **Built by**: Juan Manuel Parrilla Madrid (@jparrill)  
    **Repository**: https://github.com/jparrill/Michishirube  
    **Full Changelog**: https://github.com/jparrill/michishirube/compare/{{ .PreviousTag }}...{{ .Tag }}
    
    🤖 Generated with [Claude Code](https://claude.ai/code)

# Future Docker and Homebrew configurations can be added here

# Metadata
metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"