version: '3.8'

services:
  michishirube:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        LOAD_FIXTURES: "true"
    volumes:
      - ./data:/app/data
      # For Linux X11 forwarding
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    environment:
      # Will be overridden by platform-specific settings in Makefile
      - DISPLAY=${DISPLAY:-:0}
      - LOAD_FIXTURES=true
    # Network mode will be set by platform-specific commands in Makefile
    # Security options will be added by platform-specific commands
    restart: unless-stopped
    # Additional configuration will be applied via docker run commands in Makefile